baseURL = "https://fraxinus.jp"
title = "Fraxinus"
# for smart copyright line, leave this blank and check [params.copyright]
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""

Paginate = 5
preserveTaxonomyNames = true

enableRobotsTXT = true # generate robots.txt

# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true

enableEmoji = true

enableGitInfo = true

# Missing translations will default to this content language
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false

[params.info]
description = "Fraxinusプロジェクト"
title404 = "Nothing's here!"

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Fraxinus Project"
startYear = "2022"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#e46c0a"
hideMainMenu = false
DisableLanguageSwitchingButton = false

[params.sidebar]
enable = true

[params.widgets]
header = ["breadcrumbs"]
homepage = ["recent_posts"]
sidebar = ["about","language_select","search","sidebar_menu","taxonomy_cloud"]
footer = ["social_menu"]

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter page username

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "-"

[params.social]
email = "fraxinus-3d@googlegroups.com"
github = "fraxinus-3d"
# codepen = ""
# facebook = ""
# gitlab = ""
# instagram = ""
# linkedin = ""
# twitter = ""
# telegram = ""
# google_scholar = ""
# youtube = ""

[params.comments]
enable = false

[params.search]
client = "fuse" # algolia / fuse / lunr

[params.search.algolia]
appId = ""
indexName = ""
searchApiKey = ""

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Repo"
weight = 80
identifier = "repository"
url = "https://github.com/fraxinus-3d/docs"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.ja]
lang = "ja"
languageName = "Japanese"
weight = 1
[languages.en]
lang = "en"
languageName = "English"
weight = 10
